### ISSUE TITLE
与service进行socket通讯发生错误

### ISSUE THREAD

**Issue by jk08039527** [gtf35/app_process-shell-use#1]
failed to connect to /127.0.0.1 (port 4521) after 3000ms: isConnected failed: ECONNREFUSED (Connection refused)

**Comment by gtf35** [comment]
请检查您的service是不是成功运行了，在pc上运行dex之后数据线可拔，但usb调试不能关

**Comment by gcfchn** [comment]
是不是把usb拔掉出现的，我这也是，估计是usb拔掉后服务就结束运行了，可以用nohup命令实现断开usb后服务继续运行，如下
nohup app_process -Djava.class.path=/data/local/tmp/classes.dex /system/bin shellService.Main
