### ISSUE TITLE
静默更新不成功

### ISSUE THREAD

**Issue by lll1590** [gtf35/app_process-shell-use#11]
用你的代码跑起来了，确实能做到很多平时adb命令做不到的事情；
但是静默更新没成功，执行静默更新命令还是会弹出安装界面

手机环境：华为P20，没有root权限，Android 10
输入框命令：pm install -r xxxx.apk

请我是我操作有问题吗，望回复，谢谢

**Comment by gtf35** [comment]
很抱歉刚看到，正常 adb 安装应该也有弹窗吧，原理所限只能做到和 adb 一样的效果

**Comment by gtf35** [comment]
回复的时间太晚了，很抱歉，不知道为什么没有邮件提醒，先关闭，如果还想讨论可以重新开启
