### ISSUE TITLE
最后一步运行报错:Aborted

### ISSUE THREAD

**Issue by mdhyy008** [gtf35/app_process-shell-use#12]
134|OnePlus6:/data/local/tmp $ app_process -Djava.class.path=/data/local/tmp/classes.dex /system/bin shellService.Main

Aborted

**Comment by gtf35** [comment]
需要更多的信息，adb shell 没记错本质还是一个 apk 去执行，就叫 shell，可能是厂商定制了，最好去看看里面的代码怎么处理的。

**Comment by gtf35** [comment]
回复的时间太晚了，很抱歉，不知道为什么没有邮件提醒，先关闭，如果还想讨论可以重新开启
