### ISSUE TITLE
Permisson denied

### ISSUE THREAD

**Issue by benbenye** [gtf35/app_process-shell-use#13]
mido:/data/local/tmp $ app_process -Djava.class.path=/data/local/tmp/classes.dex /system/bin shellService.Main
th=/data/local/tmp/classes.dex /system/bin shellService.Main                  <
杩愯浜?in shell
>>>>>>Shell鏈嶅姟绔▼搴忚璋冪敤<<<<<<
鏈嶅姟绔繍琛屽湪4521绔彛

[完全按照readme操作的，结果还是没有提权

**Comment by gtf35** [comment]
很抱歉才看到，不存在没提权这种说法的，因为服务端跑在 shell 下，也就有了 shell 权限。
项目里的服务端和客户端现在看起来太简陋了，有很多的问题，但是并不是原理性的问题，而是实现上不是很好（毕竟这个代码只是证明这个思路可行）。
哦对了，你可以用 [Shizuku](https://github.com/RikkaApps/Shizuku) 来做到一样的事，原理上和这个项目是相同的

**Comment by gtf35** [comment]
回复的时间太晚了，很抱歉，不知道为什么没有邮件提醒，先关闭，如果还想讨论可以重新开启
