### ISSUE TITLE
服务保活有什么技巧吗？

### ISSUE THREAD

**Issue by Zengyonghao** [gtf35/app_process-shell-use#2]
感觉服务会死的很快 请问有什么技巧可以长期保活吗？

**Comment by puderty** [comment]
我测试也死的比较快，哪怕用nohup。并且在手机连上车机的时候目前看必死

**Comment by gtf35** [comment]
可以用一个 so 启动 dex ，然后充当守护程序，但是这个仅限于防止自己崩溃。Android 高版本的需要不关闭 USB 调试，具体可以参考黑阀。这个程序最后也没有上线，所以后续会有什么坑我也不知道  😆

**Comment by gtf35** [comment]
很久没有讨论了，先关闭
