### ISSUE TITLE
服务可以通过jni调用so，再启动service保活吗

### ISSUE THREAD

**Issue by ww275006311** [gtf35/app_process-shell-use#4]
APP可以基本实现保活，但是service无法保活，重启服务也就挂了，因此，用标题的方案，可行吗？
如执行命令前，检查服务是否存在，如果不存在，通过Java调用c，然后fork一个服务，再链接到这个服务

**Comment by gtf35** [comment]
可以直接启动 so 呀，Linux shell 那边没有保活这一说，如果是系统限制（比如手动关闭了 usb 调试等），死了就是死了，如果没手动去干预，也不会死。
回复的时间太晚了，很抱歉，不知道为什么没有邮件提醒，先关闭，如果还想讨论可以重新开启
